enum ERRORS {
  VOTE_INSERT = 'VOTE_INSERT',
  POST_VOTE = 'POST_VOTE',
  POST_UPDATE = 'POST_UPDATE',
  POST_SELECT = 'POST_SELECT',
  USER_VOTE = 'USER_VOTE',
  COMMENT_INSERT = 'COMMENT_INSERT',
  USER_COMMENT_INSERT = 'USER_COMMENT_INSERT',
  POST_COMMENT_INSERT = 'POST_COMMENT_INSERT',
  POST_INSERT = 'POST_INSERT',
  USER_CONTENT_INSERT = 'USER_CONTENT_INSERT',
  USER_POST_INSERT = 'USER_POST_INSERT',
  COMMUNITY_POST_INSERT = 'COMMUNITY_POST_INSERT',
  POST_USER_CONTENT_INSERT = 'POST_USER_CONTENT_INSERT',
  POST_FETCH = 'POST_FETCH',
  POST_ROUTE_GENERAL = 'POST_ROUTE_GENERAL',
  UCS_INSERT = 'UCS_INSERT',
  UCS_ALTER_ILLEGAL_ACTION_TYPE = 'UCS_ALTER_ILLEGAL_ACTION_TYPE',
  UCS_ID_LIST_RETRIEVE = 'UCS_ID_LIST_RETRIEVE',
}

export default ERRORS;
